---
apiVersion: v1
kind: Pod
metadata:
  name: worker
spec:
  containers:
    - name: master
      image: "{{ images.master }}"
      resources:
        requests:
          cpu: "250m"
          memory: 1Gi
        limits:
          cpu: "1"
          memory: 1Gi
      volumeMounts:
        - name: worker-workspace
          mountPath: /home/eve/workspace
    - name: mongo
      image: scality/ci-mongo:3.6.8
      imagePullPolicy: IfNotPresent
      resources:
        requests:
          cpu: 1000m
          memory: 1Gi
        limits:
          cpu: 1000m
          memory: 1Gi
  volumes:
    - name: worker-workspace
      emptyDir: {}
