name: release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to be released'
        required: true
      prerelease:
        description: "Is the release a prerelease? (true / false)"
        default: 'false'
        required: false

env:
  REGISTRY_NAME: registry.scality.com
  PROJECT_NAME: ${{ github.event.repository.name }}

jobs:
  build:
    name: Build and Push
    uses: ./.github/workflows/build.yml
    with:
      namespace: s3utils
      tag: ${{ github.event.inputs.tag }}
    secrets: inherit

  github-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Release ${{ github.event.inputs.tag }}
          tag_name: ${{ github.event.inputs.tag }}
          prerelease: ${{ github.event.inputs.prerelease }}
          generate_release_notes: true
          target_commitish: ${{ github.sha }}
