name: tests

on:
  push:
    branches-ignore:
      - development/**
      - q/*/**

concurrency:
  group: 'tests-${{ github.ref }}'
  cancel-in-progress: true

env:
  PROJECT_NAME: ${{ github.event.repository.name }}
  NAMESPACE: ${{ inputs.namespace }}
  TAG: ${{ inputs.tag }}

jobs:
  prepare:
    runs-on: ubuntu-latest
    permissions:
      # Need to explicitely add package write permissions for dependabot
      contents: read
      packages: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Docker Buildk
      uses: docker/setup-buildx-action@v2
      with:
        buildkitd-flags: --debug

    - name: Login to Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push MongoDB
      uses: docker/build-push-action@v4
      with:
        push: true
        context: .github/dockerfiles/mongodb
        tags: "ghcr.io/scality/s3utils/ci-mongodb:${{ github.sha }}"
        cache-from: type=gha
        cache-to: type=gha,mode=max

  tests:
    needs: prepare
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: ghcr.io/scality/s3utils/ci-mongodb:${{ github.sha }}
        ports:
        - 27017:27017
        - 27018:27018
        - 27019:27019
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
      - run: sudo apt-get update -q
      - run: yarn --network-concurrency 1
      - run: yarn --silent lint -- --max-warnings 0
      - run: yarn --silent test:unit
      - run: yarn --silent test:functional
        env:
          MONGODB_REPLICASET: "localhost:27018"

  build:
    name: Build and Push
    needs:
      - tests
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      namespace: s3utils-dev